//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rest.Models
{
    using System;
    using System.Collections.Generic;

        public class TableViewModel
        {
            public int TableNumber { get; set; }
            public int Capacity { get; set; }
            public string Status { get; set; }
        }
    
}
